# version: "3.9"
services:
  server:
    image: server:1.0.0
    container_name: deltadots-hapijs
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes:
      - ./server:/server
      - server-v-node-modules:/server/node_modules
    # depends_on:
    #   database:
    #     condition: service_healthy
    command: npm run debug
    # command: nodemon --inspect-brk=0.0.0.0:9229 ./server.js

  # database:
  #   image: database:1.0.0
  #   container_name: ${DB_HOST}
  #   environment:
  #     POSTGRES_HOST: ${DB_HOST}
  #     POSTGRES_PORT: ${DB_PORT}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   build:
  #     context: ./database
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   volumes:
  #     - database-v:/var/lib/postgresql/data
  #   command: "-p ${DB_PORT}"
  #   healthcheck:
  #     test:
  #       ["CMD-SHELL", "pg_isready -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME}"]
  #     start_period: 0s
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  # database-v:
  #   name: "database-v"
